apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: tictactoe-ingress
namespace: game
annotations:
alb.ingress.kubernetes.io/scheme: internet-facing
spec:
ingressClassName: alb
rules:
- host: game.example.com
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: tictactoe-service
port:
number: 80
