apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
  namespace: app2
spec:
  type: ClusterIP
  selector:
    app: tictactoe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

